# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
fail_fast: false
repos:
  - repo: local
    hooks:
      - id: black
        name: Format code (black)
        entry: black
        language: system
        types: [python]

      - id: autoflake
        name: Remove unused imports (autoflake)
        entry: autoflake
        language: system
        types: [python]
        args: [--in-place, --remove-all-unused-imports, --remove-duplicate-keys, "--remove-unused-variables", "--expand-star-imports", "--ignore-init-module-imports"]

      - id: isort
        name: Sort imports (isort)
        entry: isort
        language: system
        types: [python]

      - id: flake8
        name: Check code style and quality (flake8)
        entry: flake8
        language: system
        types: [python]

      - id: mypy
        name: Static type validation (mypy))
        entry: mypy
        language: system
        types: [python]
        pass_filenames: false
        args:
        - "ins"

      - id: yesqa
        name: Remove usless "# noqa" comments (yesqa)
        entry: yesqa
        language: system
        types: [python]

      - id: bandit
        name: Code security analysis (bandit)
        entry: bandit
        language: system
        types: [python]
        args: ["-c", "pyproject.toml", "-r", ".", "--severity=medium"]
        pass_filenames: false

      - id: liccheck
        name: Verification of package license issues (liccheck)
        entry: liccheck
        language: system
        types: [python]
        args: ["-r", "requirements.txt"]
        pass_filenames: false